services:
  backend:
    build: .
    container_name: pulsewatch-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}

  mongodb:
    image: mongo:8
    container_name: pulsewatch-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: